name: greenlandFjordsOMG

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - pandas
  - matplotlib=3.8
  - xarray
  - netcdf4
  - gsw
  - shapely
  - pyyaml
  - prettytable
  - jupyter